on:
  workflow_dispatch:

name: Clean pkgdown manually

jobs:
  pkgdown-gh-pages-manual:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CURL_SSL_BACKEND: "openssl"
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::cli
            any::rcmdcheck
            any::pkgdown
            any::reactable
            any::GADMTools
            any::rnaturalearth
            any::tidyverse
            dieghernan/pkgdev
            ropenspain/rostemplate
            ropensci/rnaturalearthhires
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, run_dont_run = TRUE, clean = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
