on:
  workflow_dispatch:

name: update-docs

jobs:
  update-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CURL_SSL_BACKEND: "openssl"
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: true


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::cli
            any::rcmdcheck
            any::pkgdown
            any::reactable
            any::rnaturalearth
            any::tidyverse
            dieghernan/pkgdev
            ropenspain/rostemplate
            ropensci/rnaturalearthhires
            IamKDO/GADMTools
          needs: website

      - name: Update docs
        run: |

          pkgdev::update_docs()

        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "dieghernan"
          git config --local user.email "dieghernan@users.noreply.github.com"
          git add -A
          git commit -m 'Update docs with pkgdev' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - uses: r-lib/actions/check-r-package@v2

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, run_dont_run = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs

